window_width: 1600
window_height: 900
window_icon: window_icon.png

window_fill_color: [57, 67, 76]
window_fill_color_theme: 
    true: [57, 67, 76]
    false: [216, 222, 233]

drawing_area_canvas_width: 2560
drawing_area_canvas_height: 1024
drawing_area_canvas_fill_color: [30, 39, 46]
drawing_area_canvas_fill_color_theme:
    true: [30, 39, 46]
    false: [216, 222, 233]
drawing_area_canvas_grid_cell_size: 64
drawing_area_canvas_grid_color: [57, 67, 76]
drawing_area_canvas_grid_color_theme:
    true: [57, 67, 76]
    false: [229, 233, 240]
drawing_area_preview_hit_box_outline_color: [229, 233, 240]
drawing_area_preview_hit_box_outline_color_theme: 
    true: [229, 233, 240]
    false: [57, 67, 76]
drawing_area_delete_selection_outline_color: [255, 94, 87]
drawing_area_preview_hit_box_outline_width: 1
drawing_area_delete_selection_outline_width: 3
drawing_area_move_selection_outline_width: 3
drawing_area_snap_threshold: 2
drawing_area_delete_highlight_color: [255, 94, 87]
drawing_area_move_highlight_color: [253, 185, 36]
drawing_area_scrolling_speed: 10
drawing_area_icon_size: [64, 64]
drawing_area_icon_player_position: drawing_area_player_position.png

hitbox_color: [229, 233, 240]
hitbox_color_theme:
    true: [229, 233, 240]
    false: [57, 67, 76]

sprite_selection_color: [76, 86, 106]

sprite_panel_fill_color: [57, 67, 76]
sprite_panel_fill_color_theme:
    true: [57, 67, 76]
    false: [229, 233, 240]
sprite_panel_padding: 10
sprite_panel_scroll_speed: 40

display_fill_color: [57, 67, 76]
display_fill_color_theme:
    true: [57, 67, 76]
    false: [229, 233, 240]
display_icon_fill_color: [229, 233, 240]
display_icon_fill_color_theme:
    true: [229, 233, 240]
    false: [57, 67, 76]
display_font_size: 16
display_icon_size: [24, 24]
display_cursor_size: 14
display_tooltip_padding: 5
display_cursor_icon_src: "display_cursor_pointer_light.png"
display_cursor_icon_src_theme:
    true: "display_cursor_pointer_light.png"
    false: "display_cursor_pointer_dark.png"
display_cursor_danger_icon_src: "display_cursor_pointer_danger.png"
display_cursor_move_src: "display_cursor_move.png"
display_cursor_player_src: "display_cursor_pointer_blue.png"
display_panning_icon_src: "display_cursor_panning_light.png"
display_panning_icon_src_theme:
    true: "display_cursor_panning_light.png"
    false: "display_cursor_panning_dark.png"
display_mode_cursor_icon_delete: "display_delete.png"
display_mode_cursor_icon_sprite: "display_sprite.png"
display_mode_cursor_icon_hitbox: "display_hitbox.png"
display_game_file_not_exists: "display_game_file_not_exists.png"
display_game_file_exists: "display_game_file_exists.png"

control_fill_color: [57, 67, 76]
control_fill_color_theme:
    true: [57, 67, 76]
    false: [229, 233, 240]
control_button_fill_color: [229, 233, 240]
control_button_fill_color_theme:
    true: [229, 233, 240]
    false: [57, 67, 76]
control_icon_size: [24, 24]

dialog_overlay_fill_color: [50, 50, 50]
dialog_box_fill_color: [57, 67, 76]
dialog_box_fill_color_theme:
    true: [57, 67, 76]
    false: [229, 233, 240]
dialog_max_box_width: 600
dialog_max_box_height: 300
dialog_font_size: 16
dialog_button_width: 100
dialog_button_height: 50
dialog_box_padding_pct: .8
dialog_inter_button_gap: 10
dialog_min_message_top_padding: 50
dialog_min_button_bottom_padding: 50

font_color: [229, 233, 240]
font_color_theme:
    true: [229, 233, 240]
    false: [57, 67, 76]
font_family: Yu Gothic Regular

theme_dependent_fields:
    - window_fill_color
    - drawing_area_canvas_fill_color
    - drawing_area_canvas_grid_color
    - drawing_area_preview_hit_box_outline_color
    - hitbox_color
    - sprite_panel_fill_color
    - display_fill_color
    - display_icon_fill_color
    - control_fill_color
    - control_button_fill_color
    - dialog_box_fill_color
    - font_color
    - display_cursor_icon_src
    - display_panning_icon_src

dark_theme: true

icon_directory: "./resources/images/icons"
font_directory: "./resources/fonts"
font_file_name:
    Arabic: "Arabic-NotoSans-Light.ttf"
    Burmese: "Burmese-NotoSans-Light.ttf"
    English: "NotoSans-Light.ttf"
    Spanish: "NotoSans-Light.ttf"
    French: "NotoSans-Light.ttf"
    Japanese: "Japanese-NotoSans-Light.ttf"
    Chinese: "Chinese-NotoSans-Light.ttf"
sprite_directory: "."
map_output_directory: "."
map_output_filename: map.json
user_config_filename: user-config.yml

modes:
    - sprite
    - hitbox
    - delete
    - player
    - move


# Colors for reference
light_purple: [112, 111, 211]
dark_purple: [64, 64, 122]

light_grey: [247, 241, 227]
dark_grey: [170, 166, 157]

light_green: [51, 217, 178]
dark_green: [33, 140, 116]

light_red: [255, 82, 82]
dark_red: [179, 57, 57]

light_blue: [52, 172, 224]
dark_blue: [34, 112, 147]

light_orange: [255, 121, 63]
dark_orange: [205, 97, 51]

light_yellow: [255, 218, 121]
dark_yellow: [255, 177, 66]

# Paths to bundle
path_fields:
    - game_runner_game_executable_path
    - icon_directory
    - font_directory
    - sprite_directory
    - map_output_directory

language: "English"
language_config_field:
    label: Language
    type: str_options
    options: 
        - English
    default_value: English
language_file_name: temp_language.txt
language_file_directory: "."
user_config_filename: user_config.yml
user_config_directory: "."

ui_user_definable_fields:
    window_width:
        label: Windiw Width
        type: int
    window_height:
        label: Window Height
        type: int
    drawing_area_canvas_width:
        label: Level Map Width
        type: int
    drawing_area_canvas_height:
        label: Level Map Height
        type: int
    drawing_area_canvas_grid_cell_size:
        label: Size of grid cells
        type: int
    drawing_area_snap_threshold:
        label: Snapping Threshold
        type: int
    game_runner_game_executable_path:
        label: Game Executable Path
        type: file
    sprite_directory:
        label: Sprite Directory
        type: directory
        default_value: "."
        required: true
    map_output_directory:
        label: Map Output Directory
        type: directory
        default_value: "."
        required: true
    dark_theme:
        label: Dark Theme
        default_value: true
        type: bool

i18n:
    English:
        app:
            window_title: Map Editor
            config_ui:
                window_title:
                    browse_game_executable_file: Browse Game Executable
                    initial_configuration: Initial Configuration
                    browse_map_data_file_path: Browse Level Data File
                game_executable_path_label: Game Executable Path
                all_set: All Set
                set_button: Set
                cancel_button: Cancel
                browse: Browse
                default: Default
                labels:
                    drawing_area_canvas_width: Level Map Width
                    drawing_area_canvas_height: Level Map Height
                    game_runner_game_executable_path: Game Executable Path
                    sprite_directory: Sprite Directory
                    map_output_directory: Map Output Directory
                    dark_theme: Dark Theme
                    language: Language
                    drawing_area_canvas_grid_cell_size: Canvas Grid Size
                    drawing_area_snap_threshold: Snapping Distance
                    window_width: Window Width
                    window_height: Window Height
                    map_data_file_path: Level Data File
            dialogs:
                no_game_specified:
                    message: You have not specified a game to run!
                    add_game_button: Add game
                    back_button: Back
                unsaved_changes_run:
                    message: You have unsaved changes. Run with old map?
                    just_run_button: Just run
                    save_first_button: Save first
                unsaved_changes_quit:
                    message: You have unsaved changes. Quit?
                    just_quit_button: Just quit
                    save_first_button: Save first
                current_design_will_be_replaced: 
                    message: Your current level design will be replaced without saving
                    just_load: Just Load
                    save_first: Save First
                map_data_sprite_mismatch:
                    message: The map data doesn't match with the sprites
                    load_another: Load another
                    cancel: Cancel
                user_config_cleared:
                    message: User config cleared successfully
                    ok: OK
                user_config_not_cleared:
                    message: Failed to clear user config. Do it manually
                    ok: OK
            controls:
                save:
                    hint_disabled: No changes to save
                    hint_enabled: Save level data
                load:
                    hint_enabled: Load a level map
                delete:
                    hint_disabled_already_in_mode: Already in delete mode
                    hint_disabled_no_objects: Can't switch to delete-mode with no objects to delete
                    hint_enabled: Switch to delete mode
                run:
                    hint_disabled_running: 'Can''t run the game now, stop the running game'
                    hint_disabled_no_objects: 'Can''t run the game now, add level objects'
                    hint_enabled: Run the selected game
                stop:
                    hint_disabled: No running game to stop
                    hint_enabled: Stop the running game
                game_file:
                    hint_disabled: Can't load file
                    hint_enabled: Load a game file to be run
                player:
                    hint_disabled: Already in player mode
                    hint_enabled: Switch to player position mode
                move:
                    hint_disabled_no_sprites_to_move: There are no sprites yet to move
                    hint_disabled_already_in_move_mode: Already in move mode
                    hint_enabled: Switch to moving mode
                clear_user_config:
                    hint_disabled: User config already cleared
                    hint_enabled: Clear user config
            display:
                game_file_status_no_game: No game loaded
                game_file_status_game_loaded: Game loaded
                mode_sprite: Sprite mode
                mode_sprite_hint: Click once to place a sprite
                mode_hitbox: Hitbox mode
                mode_hitbox_hint: Click and drag to draw a hitbox
                mode_delete: Delete mode
                mode_delete_hint: Click once to delete a sprite or a hitbox, or click and drag to bulk delete (sprites and hitboxes)
                mode_player: Player position mode
                mode_player_hint: Click once to place the player's starting position
                mode_move: Moving mode
                mode_move_hint: Click, hold, and drag to move a sprite around the canvas